# Generated by Django 5.0.6 on 2024-06-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarbucksApp', '0002_remove_order_user_order_customer_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
